name: Fix Sermon Sync

on:
  workflow_dispatch:  # Manual trigger only

permissions:
  contents: write

jobs:
  fix-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Force reset to remote state
        run: |
          git config --global user.name "Sermon Transcription Bot"
          git config --global user.email "fellowship-digital-ministry@proton.me"
          git fetch origin
          git reset --hard origin/main
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Setup FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
      - name: Setup Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pandas yt-dlp python-dotenv
      
      - name: Process sermons
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd transcription
          python monitor_channel.py --channel-id UCek_LI7dZopFJEvwxDnovJg --process --cleanup
      
      - name: Force push changes
        run: |
          git add transcription/data/transcripts/
          git add transcription/data/metadata/
          git add transcription/data/video_list.csv
          git status
          git diff --staged --quiet || git commit -m "Add new sermon transcripts [skip ci]"
          git push -f