name: Podcast RSS Ingest
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  podcast-ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install feedparser requests yt-dlp pydub pandas openai pinecone
          sudo apt-get update
          sudo apt-get install -y ffmpeg
      - name: Run podcast monitor
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python transcription/monitor_podcast.py \
            --feed-url "https://fbcministries.net/feed/podcast" \
            --process
      - name: Transcribe podcast audio
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python transcription/transcribe_audio.py
      - name: Generate embeddings for transcripts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT || 'us-east-1' }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME || 'sermon-embeddings' }}
        run: |
          python tools/transcript_to_embeddings.py --skip_existing
      - name: Update Pinecone metadata
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT || 'us-east-1' }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME || 'sermon-embeddings' }}
        run: |
          python api/update_pinecone_metadata.py --only-recent --days=7
      - name: Commit and push changes
        run: |
          git config --local user.name "Sermon Bot"
          git config --local user.email "sermon-bot@example.com"
          git add transcription/data podcast_monitor.log requirements.txt
          git diff --staged --quiet && echo "No changes" || git commit -m "Process podcast feed [skip ci]"
          git push