name: Transcribe Sermons

permissions:
  contents: write  # Grant write access to push changes

on:
  schedule:
    # Run once a week on Sunday at 2 AM UTC
    - cron: '0 20 * * 1,4'
  workflow_dispatch:  # Allows manual triggering

jobs:
  transcribe:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives write permission to the repository contents
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for commits
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN for authentication
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yt-dlp openai tqdm python-dotenv pydub
      
      - name: Configure Git
        run: |
          git config --global user.name "Sermon Transcription Bot"
          git config --global user.email "fellowship-digital-ministry@proton.me"
      
      - name: Run sermon monitoring and processing
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          cd transcription
          python monitor_channel.py --channel "https://www.youtube.com/@chrismann9821" --process --cleanup
      
      - name: Commit and push changes
        run: |
          git add transcription/data/transcripts/
          git add transcription/data/metadata/
          git add transcription/data/video_list.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Add new sermon transcripts and subtitles [skip ci]" && git push)