name: Transcribe and Embed Sermons

on:
  schedule:
    # Run every day at 7AM UTC
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allows manual triggering

# Add permissions block
permissions:
  contents: write

jobs:
  transcribe:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full history for commits
          token: ${{ secrets.PAT_TOKEN }}  # Use a Personal Access Token
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install required dependencies
          pip install pandas openai tqdm pydub pytube requests
          # Install the correct Pinecone package
          pip uninstall -y pinecone-client
          pip install pinecone
          # Just in case of fallback, also install yt-dlp
          pip install --upgrade yt-dlp
      
      - name: Configure Git
        run: |
          git config --global user.name "Sermon Transcription Bot"
          git config --global user.email "fellowship-digital-ministry@proton.me"
      
      - name: Run sermon monitoring with YouTube API
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: |
          # Output current time for logging
          date
          echo "Starting sermon monitoring process using YouTube API"
          
          # Create output directories
          mkdir -p transcription/data/audio
          
          # Run the monitoring script with YouTube API - using direct channel ID
          cd transcription
          python monitor_channel.py \
            --youtube-api \
            --api-key "$YOUTUBE_API_KEY" \
            --channel-id "UCek_LI7dZopFJEvwxDnovJg" \
            --max 5 \
            --process \
            --cleanup
        shell: bash
      
      # Add fallback method in case the API approach fails
      - name: Run fallback sermon monitoring if needed
        if: ${{ failure() }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
        run: |
          echo "API approach failed, trying fallback method with yt-dlp"
          
          # Create cookies file if provided
          if [ -n "$YOUTUBE_COOKIES" ]; then
            echo "# Netscape HTTP Cookie File" > youtube_cookies.txt
            echo "# https://curl.haxx.se/docs/http-cookies.html" >> youtube_cookies.txt
            echo "# This file was generated by libcurl! Edit at your own risk." >> youtube_cookies.txt
            echo "" >> youtube_cookies.txt
            echo "$YOUTUBE_COOKIES" >> youtube_cookies.txt
            chmod 600 youtube_cookies.txt
            COOKIES_PARAM="--cookies youtube_cookies.txt"
          else
            COOKIES_PARAM=""
          fi
          
          # Run the fallback approach
          cd transcription
          python monitor_channel.py \
            --channel "https://www.youtube.com/@chrismann9821" \
            --max 5 \
            --process \
            --cleanup \
            $COOKIES_PARAM
          
          # Clean up cookies file
          rm -f youtube_cookies.txt
        shell: bash
      
      # Add the embedding step
      - name: Generate embeddings for new transcripts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT || 'us-east-1' }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME || 'sermon-embeddings' }}
        run: |
          python tools/transcript_to_embeddings.py --skip_existing
      
      # Update metadata in Pinecone
      - name: Update Pinecone metadata from JSON files
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT || 'us-east-1' }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME || 'sermon-embeddings' }}
        run: |
          # Copy the metadata utilities to the tools directory
          cp api/metadata_utils.py tools/
          
          # Run the metadata update script for only recent changes
          python api/update_pinecone_metadata.py --only-recent --days=7
      
      # First pull latest changes before committing
      - name: Pull latest changes
        run: git pull origin main
        
      - name: Commit and push changes
        run: |
          git add transcription/data/transcripts/
          git add transcription/data/metadata/
          git add transcription/data/video_list.csv
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add new sermon transcripts and subtitles [skip ci]"
            git push
          fi